// Code generated by govld-gen; DO NOT EDIT.

package internal

import (
	"context"
	"fmt"
	"go.osspkg.com/validate"
)

// ValidateUIDAdaptHandler is adapter for ValidateUID.
func ValidateUIDAdaptHandler(ctx context.Context, value any, opts ...any) (err error) {
	var typedValue int64
	switch v := value.(type) {
	case string:
		if err = validate.StringDecode(&typedValue, v); err != nil {
			return fmt.Errorf("convert value to int64: %w", err)
		}
	case int64:
		typedValue = v
	default:
		return fmt.Errorf("ValidateUID: expected value of type int64, got %T", value)
	}

	if len(opts) != 1 {
		return fmt.Errorf("ValidateUID: expected 1 opts, got %d", len(opts))
	}

	var opt0 int64
	switch v := opts[0].(type) {
	case string:
		if err = validate.StringDecode(&opt0, v); err != nil {
			return fmt.Errorf("convert opt0 to int64: %w", err)
		}
	case int64:
		opt0 = v
	default:
		return fmt.Errorf("ValidateUID: expected opt[0] of type int64, got %T", opts[0])
	}

	return ValidateUID(ctx, typedValue, opt0)
}

// ValidateGIDAdaptHandler is adapter for ValidateGID.
func ValidateGIDAdaptHandler(ctx context.Context, value any, opts ...any) (err error) {
	var typedValue int64
	switch v := value.(type) {
	case string:
		if err = validate.StringDecode(&typedValue, v); err != nil {
			return fmt.Errorf("convert value to int64: %w", err)
		}
	case int64:
		typedValue = v
	default:
		return fmt.Errorf("ValidateGID: expected value of type int64, got %T", value)
	}

	if len(opts) != 1 {
		return fmt.Errorf("ValidateGID: expected 1 opts, got %d", len(opts))
	}

	var opt0 GUID
	switch v := opts[0].(type) {
	case string:
		if err = validate.StringDecode(&opt0, v); err != nil {
			return fmt.Errorf("convert opt0 to GUID: %w", err)
		}
	case GUID:
		opt0 = v
	default:
		return fmt.Errorf("ValidateGID: expected opt[0] of type GUID, got %T", opts[0])
	}

	return ValidateGID(ctx, typedValue, opt0)
}
