package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/types"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"golang.org/x/tools/go/packages"
)

const (
	defaultFileName = "adapt_handlers_gen.go"
	generateTag     = "//govld:gen"
)

func main() {
	pkgPath := flag.String("pkg", ".", "path to pkg (example ./...)")
	flag.Parse()

	cfg := &packages.Config{
		Mode: packages.NeedTypes | packages.NeedSyntax | packages.NeedTypesInfo | packages.NeedName | packages.NeedFiles,
	}

	pkgs, err := packages.Load(cfg, *pkgPath)
	if err != nil {
		log.Fatalf("load packages: %v", err)
	}
	if len(pkgs) == 0 {
		log.Fatal("packages not found")
	}

	for _, pkg := range pkgs {
		if len(pkg.Errors) > 0 {
			log.Fatalf("packege errors: %v", pkg.Errors)
		}

		var funcs []*ast.FuncDecl
		for _, file := range pkg.Syntax {
			for _, decl := range file.Decls {
				fd, ok := decl.(*ast.FuncDecl)
				if !ok || fd.Doc == nil {
					continue
				}
				for _, comment := range fd.Doc.List {
					if strings.TrimSpace(comment.Text) == generateTag {
						funcs = append(funcs, fd)
						break
					}
				}
			}
		}

		if len(funcs) == 0 {
			continue
		}

		info := pkg.TypesInfo
		gen := generator{
			pkg:       pkg,
			funcs:     funcs,
			info:      info,
			imports:   make(map[string]string), // path -> alias
			usedPkgs:  make(map[string]bool),
			qualifier: nil,
		}
		gen.qualifier = gen.makeQualifier()

		{
			gen.usedPkgs["context"] = true
			gen.usedPkgs["fmt"] = true

			gen.usedPkgs["go.osspkg.com/validate"] = true
			gen.imports["go.osspkg.com/validate"] = "validate"
		}

		outFile := filepath.Join(pkg.Dir, defaultFileName)

		if err = gen.generate(outFile); err != nil {
			log.Fatalf("generate `%s`: %v", outFile, err)
		}

		log.Println("done", outFile)
	}

}

type generator struct {
	pkg       *packages.Package
	funcs     []*ast.FuncDecl
	info      *types.Info
	imports   map[string]string // collected imports (path -> local name, if needed)
	usedPkgs  map[string]bool   // which packages are actually used in the generated code
	qualifier types.Qualifier
}

func (g *generator) makeQualifier() types.Qualifier {
	self := g.pkg.Types
	return func(other *types.Package) string {
		if other == self {
			return ""
		}
		g.usedPkgs[other.Path()] = true
		return other.Name()
	}
}

func (g *generator) generate(filename string) error {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by govld-gen; DO NOT EDIT.\n\n")
	buf.WriteString(fmt.Sprintf("package %s\n\n", g.pkg.Name))

	var funcBodies bytes.Buffer
	for _, fd := range g.funcs {
		fnObj := g.info.Defs[fd.Name].(*types.Func)
		sig := fnObj.Type().(*types.Signature)

		params := sig.Params()
		if params.Len() < 2 {
			log.Printf("skip `%s`: not enough parameters", fd.Name)
			continue
		}

		firstParam := params.At(0)
		if !isContextType(firstParam.Type()) {
			log.Printf("skip `%s`: first parameter is not context.Context", fd.Name)
			continue
		}

		valueParam := params.At(1)
		optParams := make([]*types.Var, 0)

		for i := 2; i < params.Len(); i++ {
			optParams = append(optParams, params.At(i))
		}

		g.emitWrapper(&funcBodies, fd.Name.Name, valueParam, optParams)
	}

	var importLines []string
	if len(g.usedPkgs) > 0 {
		importLines = append(importLines, "import (")

		var paths []string
		for p := range g.usedPkgs {
			paths = append(paths, p)
		}

		sort.Strings(paths)

		for _, p := range paths {
			alias := g.imports[p]
			if alias == "" {
				alias = pkgNameFromPath(p)
			}
			if alias == g.pkg.Name && p != g.pkg.PkgPath {
				alias = alias + "_import"
			}
			importLines = append(importLines, fmt.Sprintf("\t\"%s\"", p))
		}

		importLines = append(importLines, ")")
	}

	buf.WriteString(strings.Join(importLines, "\n"))
	buf.WriteString("\n\n")
	buf.Write(funcBodies.Bytes())

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		_ = os.WriteFile(filename+".debug", buf.Bytes(), 0644)
		return fmt.Errorf("go format: %w", err)
	}

	return os.WriteFile(filename, formatted, 0644)
}

func (g *generator) emitWrapper(w *bytes.Buffer, name string, value *types.Var, opts []*types.Var) {
	q := g.qualifier
	valTypeStr := types.TypeString(value.Type(), q)
	fmt.Fprintf(w, "// %sAdaptHandler is adapter for %s.\n", name, name)
	fmt.Fprintf(w, "func %sAdaptHandler(ctx context.Context, value any, opts ...any) (err error) {\n", name)

	fmt.Fprintf(w, "var typedValue %s\n", valTypeStr)
	fmt.Fprintf(w, "switch v := value.(type) {\n")
	fmt.Fprintf(w, "case string:\n")
	fmt.Fprintf(w, "if err = validate.StringDecode(&typedValue, v); err != nil {")
	fmt.Fprintf(w, "return fmt.Errorf(\"convert value to %s: %%w\", err)\n}\n", valTypeStr)
	fmt.Fprintf(w, "case %s:\n", valTypeStr)
	fmt.Fprintf(w, "typedValue = v\n")
	fmt.Fprintf(w, "default:\n")
	fmt.Fprintf(w, "return fmt.Errorf(\"%s: expected value of type %s, got %%T\", value)\n", name, valTypeStr)
	fmt.Fprintf(w, "}\n")
	fmt.Fprintf(w, "\n")

	if len(opts) > 0 {
		fmt.Fprintf(w, "if len(opts) != %d {\n", len(opts))
		fmt.Fprintf(w, "return fmt.Errorf(\"%s: expected %d opts, got %%d\", len(opts))\n", name, len(opts))
		fmt.Fprintf(w, "}\n")
		fmt.Fprintf(w, "\n")

		for i, param := range opts {
			optTypeStr := types.TypeString(param.Type(), q)

			fmt.Fprintf(w, "var opt%d %s\n", i, optTypeStr)
			fmt.Fprintf(w, "switch v := opts[%d].(type) {\n", i)
			fmt.Fprintf(w, "case string:\n")
			fmt.Fprintf(w, "if err = validate.StringDecode(&opt%d, v); err != nil {", i)
			fmt.Fprintf(w, "return fmt.Errorf(\"convert opt%d to %s: %%w\", err)\n}\n", i, optTypeStr)
			fmt.Fprintf(w, "case %s:\n", optTypeStr)
			fmt.Fprintf(w, "opt%d = v\n", i)
			fmt.Fprintf(w, "default:\n")
			fmt.Fprintf(w, "return fmt.Errorf(\"%s: expected opt[%d] of type %s, got %%T\", opts[%d])\n", name,
				i, optTypeStr, i)
			fmt.Fprintf(w, "}\n")
			fmt.Fprintf(w, "\n")
		}
	}

	fmt.Fprintf(w, "return %s(ctx, typedValue", name)
	for i := range opts {
		fmt.Fprintf(w, ", opt%d", i)
	}
	fmt.Fprintf(w, ")\n")
	fmt.Fprintf(w, "}\n\n")
}

func isContextType(t types.Type) bool {
	named, ok := t.(*types.Named)
	if !ok {
		return false
	}
	return named.Obj().Pkg() != nil && named.Obj().Pkg().Path() == "context" && named.Obj().Name() == "Context"
}

func pkgNameFromPath(path string) string {
	idx := strings.LastIndex(path, "/")
	if idx >= 0 {
		return path[idx+1:]
	}
	return path
}
